# Generated by Django 4.2 on 2023-04-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('natura', '0001_create_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(default='')),
                ('image_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='natura.products')),
            ],
        ),
    ]
