# Generated by Django 4.2 on 2023-04-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natura', '0003_images_image_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_activeIngredient',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_longDescription',
            field=models.TextField(default=''),
        ),
    ]
