# Generated by Django 4.2 on 2023-05-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natura', '0004_alter_products_product_activeingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_activeIngredient',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_longDescription',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_usage',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
